# Generated by Django 6.0.4 on 2026-04-29 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('manager_email', models.EmailField(max_length=254)),
                ('skills', models.CharField(blank=True, help_text='Comma separated skills', max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, help_text='Brief mission statement or purpose of the team.', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed responsibilities.', null=True)),
                ('code_repos', models.JSONField(blank=True, default=list, help_text='List of repository names.')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('upstream', models.ManyToManyField(blank=True, help_text='Teams this team depends on.', related_name='downstream', to='teams.team')),
            ],
        ),
    ]
