# Generated by Django 6.0.4 on 2026-04-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependency',
            options={'verbose_name_plural': 'Dependencies'},
        ),
    ]
